[package]
name = "noir_basics"
entry = "vectors.nr"
type = "bin"
authors = [""]
compiler_version = "0.9.0"

[dependencies]
u2b = { tag = "v0.3.0-nightly", git = "https://github.com/codingnirvana/noir-u2b" }